### ISSUE TITLE
Add  emoji support to ChatBud

### ISSUE THREAD

**Issue by bhargav794** [guptasajal411/instant-chat-app#13]
add an emoji picker so that users can send emoji's in the chat

**Comment by guptasajal411** [comment]
Chatbud now supports emojis 🎉 Check the deploy here: https://try-chatbud.herokuapp.com/

### Screenshots
![image](https://user-images.githubusercontent.com/70312106/132048788-64efe622-3b95-4c2e-8ba5-3fff9499c5b0.png)
![image](https://user-images.githubusercontent.com/70312106/132048820-cac9ed68-6396-4fae-a1a1-d22d6cac5770.png)
