### ISSUE TITLE
Make a public folder and add JS to it

### ISSUE THREAD

**Issue by guptasajal411** [guptasajal411/instant-chat-app#5]
# Welcome to Chatbud!

For having a better project structure, we have to do some changes in the project directory.
Just leave a comment and I will assign this issue to you

Steps to be followed:
1. Create a folder named "public" in the main directory.
2. Create two folders inside "public", named "js" and "css".
3. Move `index.js` from main directory to "js" folder.
4. Move `styles.css` from main directory to "css" folder.

That's it!
After following these steps, raise a Pull Request and I will review and merge your changes!

**Comment by Shubh28698** [comment]
Hey Sajal,

I am new into open source contribution world and i have already done the changes. can u please assign it to me because its saying " access denied".

Thank you

**Comment by guptasajal411** [comment]
Hey Shubham, 
Thanks for raising interest in this project. I have assigned this issue to you. 
Raise a pull request so I can merge your contributions to this project.

**Comment by guptasajal411** [comment]
Thanks for your contribution, Shubham! 🚀 Your PR has been successfully merged and the changes have been deployed to Heroku. You can check out the app **[here.](https://try-chatbud.herokuapp.com/)**
