### ISSUE TITLE
Add number of connected clients to Chatbud

### ISSUE THREAD

**Issue by guptasajal411** [guptasajal411/instant-chat-app#7]

**Comment by bhargav794** [comment]
hello, Sajal
I'm looking to contribute to open source projects can you assign this one to me. I will do  my best to achieve it
Thank you.

**Comment by guptasajal411** [comment]
Hey there!
Thanks for showing interest in Chatbud. Actually this issue was self-assigned, which means that I am already working on this feature. But if you make a working pull request before me, I will merge that for sure.
If you have any doubts while working, don't hesitate to ask me, I have to beautify some code 😅

**Comment by bhargav794** [comment]
>But if you make a working pull request before me, I will merge that for sure.

Thank you so much
>If you have any doubts while working, don't hesitate to ask me, I have to beautify some code 😅

will do.

**Comment by bhargav794** [comment]
I made the change and submitted PR. Do let me know if you want any more changes regarding this issue @guptasajal411

**Comment by guptasajal411** [comment]
Thanks for your contribution! You PR is merged and has been deployed. Find the deployed site **[here.](https://try-chatbud.herokuapp.com/)**
