### ISSUE TITLE
Update UI for mobile viewports

### ISSUE THREAD

**Issue by guptasajal411** [guptasajal411/instant-chat-app#8]
# Welcome to Chatbud!

<img src = "https://user-images.githubusercontent.com/70312106/128629123-09949ff2-c66a-40fa-8586-53edf3ee1dba.png" width = 350px alt="Screenshot of Chatbud in mobile viewports">

The web app looks too small to chat with in mobile viewports. I think that using some media queries for the messages and the input section will solve the problem.

I would love to hear from you! Drop me a message and I will assign this issue to you.

**Comment by adityakmr7** [comment]
Can assign it to me I will have a look at this.

**Comment by guptasajal411** [comment]
Yes sure @adityakmr7!
Reach out to me if you have any problems or doubts in the codebase.

**Comment by guptasajal411** [comment]
It works great now!
### Screenshots
![image](https://user-images.githubusercontent.com/70312106/129019886-375b99dd-8ebb-4fca-b93d-2c02511b5bb9.png)

Thanks for teaching me about the viewport meta tag

**Comment by guptasajal411** [comment]
Thanks for your contribution, Aditya 🚀
